### PR TITLE
feat: ✨ add a json parser

### PR DESCRIPTION
**Pull request by gwealm**
This pull request's main objective is to discuss about the json parser and which improvements and changes could be made.
@limwa @Naapperas Give me your feedback

### CODE REVIEW

**Comment by gui1612** [comment]
This pull request's main objective is to discuss about the json parser and which improvements and changes could be made.
@limwa @Naapperas Give me your feedback

**Comment by gui1612** [comment]
Also, I don't believe that importing OS is particularly necessary, since .json file and the parser are in the same folder, but I decided to keep until you tell me something about it.

**Comment by limwa** [comment]
I am not comfortable in approving this solution. Let's wait for a few more days and then start discussing this.

**Comment by gwealm** [comment]
> I am not comfortable in approving this solution. Let's wait for a few more days and then start discussing this.

Alright, not a problem. Feel free to change whatever you want, even the full resolution itself

**Comment by limwa** [comment]
Please close this pull request. As discussed, we will not be pursuing this.

**Comment by limwa** [comment]
Nevermind xD

**Pull request closed without merging**
